### ISSUE TITLE
Please Release Version: 4.1.2

### ISSUE THREAD

**Issue by fullopt** [webjars/chartjs#23]
Please ensure the package contains minified files as well.

**Comment by jamesward** [comment]
This will be released shortly.

**Comment by fullopt** [comment]
Why the chart.min.js file are not included in dist? Thanks.

**Comment by jamesward** [comment]
The WebJar is just the contents of the release tar.gz from: https://github.com/chartjs/Chart.js/releases  So whatever is in there should be in the WebJar.  Let me know if not.
